name: charum
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  dio: ^5.4.3+1
  image_cropper: ^5.0.1
  image_picker: ^1.1.0
  shared_preferences: ^2.2.3
  cached_network_image: ^3.3.1
  email_validator: ^2.1.17
  go_router: ^14.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/welcome/
    - assets/social-media-logo/
    - assets/topics/

flutter_native_splash:
  image: assets/logo/charum-logo.png
  color: "#178066"
  android: true
  ios: true
